### ISSUE TITLE
offline check-in data: support delta requests + optional data

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io-PI#11]
see https://github.com/exteso/alf.io/issues/319,
request incremental modifications instead of the whole dataset

**Comment by syjer** [comment]
TODO:

 - [x] remove the eventAttendeesCache and switch to a db representation + add new table for saving: [event, uuid, payload, last_change]
 - [ ] send timestamp

**Comment by syjer** [comment]
re-update to the new api, see exteso/alf.io#319
