### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by proffalken** [exteso/alf.io-PI#81]
Hello,

We've just adopted Alf for our Makerspace and it looks like this project could be really useful as well.

I've noticed that the current `0.9-maintenance` branch has not been updated in some time, and `v2` is even older.

Is Alf.io-PI something that is still being maintained, or should I be looking at using Backoffice instead?

**Comment by syjer** [comment]
hi, @proffalken , thank you for using alfio =).

So, the alf.io-PI project is for handling the check-in + badge printing, you can see the documentation here https://alf.io/docs/event-management/check-in/stations/  , it currently work, it's  actively used for events (even big ones!), but  the setup is quite involved.

Most likely, you want to keep it simple, thus the mobile app: https://alf.io/docs/event-management/check-in/check-in-app/ (source code: https://github.com/alfio-event/Alf.ioBackoffice ) might be easier to start with.

To answer your initial question: yes it's currently maintained, as it is supported and officially used, we have reached all the features required for our use cases, thus the lack of commit.

To be noted, when we will have time, we will revisit the alf.io-PI project.

**Comment by proffalken** [comment]
Amazing, thanks - I've switched over from Eventbrite and Facebook to Alf.io and I'm very impressed so far.

Knowing that I can print badges etc as well is even better, and if this is "feature complete" then that's great!
