### ISSUE TITLE
on screen "touch" keyboard

### ISSUE THREAD

**Issue by syjer** [exteso/alf.io-PI#9]
For the angular app, when using the touch screen.

**Comment by cbellone** [comment]
see https://protacon.github.io/ng-virtual-keyboard/

**Comment by cbellone** [comment]
- [ ] responsive layout
- [ ] multiple keyboard layouts or "SYM" key with all special chars (àéöüè...)

**Comment by syjer** [comment]
TODO:

- [ ] import material icons instead of linking
- [ ] enable only on a small screen
